FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
# Use native linux file polling for better performance
ENV ASPNETCORE_ENVIRONMENT Development
ENV DOTNET_USE_POLLING_FILE_WATCHER 1

WORKDIR /app

#COPY ["ToDoList/ToDoList.csproj", "ToDoList/"]
#RUN dotnet restore "ToDoList/ToDoList.csproj"
#COPY . .
#WORKDIR "/src/ToDoList"
#RUN dotnet build "ToDoList.csproj" -o /app

ENTRYPOINT dotnet watch run --project ToDoList --launch-profile Docker
