version: '3.7'

networks:
  web-realese:
    driver: bridge

services:
  db:
    image: postgres
    volumes:
      - ./db/:/var/lib/postgres/data/
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=db
    ports:
      - 5432:5432
    networks:
      - web-realese

  mvc:
    image: mvc
    build:
      context: .
      dockerfile: ToDoList/Dockerfile
    ports:
      - "5199:8080"
    networks:
      - web-realese

